#!/bin/bash
#Test
#Ping Sweep team0
for ips in {10,20,30,40}; do (ping 192.168.0.$ips -c 1 >/dev/null)
        if [ $? -eq 0 ]
        then
		echo Up > /var/www/html/web/teams/team0/pingup/$ips;
                points=5;
                current=$(cat /var/www/html/web/teams/team0/points);
                echo "DMZ VM "$ips" earned "$points" points";
                expr $current + $points > /var/www/html/web/teams/team0/points
        else
		echo Down > /var/www/html/web/teams/team0/pingup/$ips;
                echo "DMZ VM "$ips" interface is down";
                expr $current > /var/www/html/web/teams/team0/points;
        fi
done

