#!/bin/bash
#TEst
#Web Sweep DMZ
if [ $? -eq 0 ]
then
        content=$(curl 127.0.0.1)
        echo $content
        if [ $content == "Test" ]
        then
        echo Up > /var/www/html/web/teams/team0/webup/10;
	points=5;
        current=$(cat /var/www/html/web/teams/team0/points);
        echo "Team "$ips" earned "$points" points";
        expr $current + $points > /var/www/html/web/teams/team0/points
        else
	echo Down > /var/www/html/web/teams/team0/webup/10;
        echo Web is down
	fi
else
	echo Error Code
fi

